# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'ZenDoodle' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZenDoodle
  pod 'MaterialControls', '~> 1.0.2'

  target 'ZenDoodleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZenDoodleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
